In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
books = pd.read_csv('/books.csv')
books

id  book_id  best_book_id   work_id  books_count        isbn  \
0         1  2767052       2767052   2792775          272   439023483   
1         2        3             3   4640799          491   439554934   
2         3    41865         41865   3212258          226   316015849   
3         4     2657          2657   3275794          487    61120081   
4         5     4671          4671    245494         1356   743273567   
...     ...      ...           ...       ...          ...         ...   
9995   9996  7130616       7130616   7392860           19   441019455   
9996   9997   208324        208324   1084709           19  067973371X   
9997   9998    77431         77431   2393986           60  039330762X   
9998   9999  8565083       8565083  13433613            7    61711527   
9999  10000     8914          8914     11817           31   375700455   

            isbn13                      authors  original_publication_year  \
0     9.780439e+12              Suzanne Collins                     2008.0   
1     9.780440e+12  J.K. Rowling, Mary GrandPré                     1997.0   
2     9.780316e+12              Stephenie Meyer                     2005.0   
3     9.780061e+12                   Harper Lee                     1960.0   
4     9.780743e+12          F. Scott Fitzgerald                     1925.0   
...            ...                          ...                        ...   
9995  9.780441e+12                Ilona Andrews                     2010.0   
9996  9.780680e+12               Robert A. Caro                     1990.0   
9997  9.780393e+12              Patrick O'Brian                     1977.0   
9998  9.780062e+12              Peggy Orenstein                     2011.0   
9999  9.780376e+12                  John Keegan                     1998.0   

                                         original_title  ... ratings_count  \
0                                      The Hunger Games  ...       4780653   
1              Harry Potter and the Philosopher's Stone  ...       4602479   
2                                              Twilight  ...       3866839   
3                                 To Kill a Mockingbird  ...       3198671   
4                                      The Great Gatsby  ...       2683664   
...                                                 ...  ...           ...   
9995                                         Bayou Moon  ...         17204   
9996                                   Means of Ascent   ...         12582   
9997                              The Mauritius Command  ...          9421   
9998  Cinderella Ate My Daughter: Dispatches from th...  ...         11279   
9999                                The First World War  ...          9162   

     work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
0               4942365                   155254      66715     127936   
1               4800065                    75867      75504     101676   
2               3916824                    95009     456191     436802   
3               3340896                    72586      60427     117415   
4               2773745                    51992      86236     197621   
...                 ...                      ...        ...        ...   
9995              18856                     1180        105        575   
9996              12952                      395        303        551   
9997              10733                      374         11        111   
9998              11994                     1988        275       1002   
9999               9700                      364        117        345   

      ratings_3  ratings_4  ratings_5  \
0        560092    1481305    2706317   
1        455024    1156318    3011543   
2        793319     875073    1355439   
3        446835    1001952    1714267   
4        606158     936012     947718   
...         ...        ...        ...   
9995       3538       7860       6778   
9996       1737       3389       6972   


In [8]:
books.columns

Index(['id', 'book_id', 'best_book_id', 'work_id', 'books_count', 'isbn',
       'isbn13', 'authors', 'original_publication_year', 'original_title',
       'title', 'language_code', 'average_rating', 'ratings_count',
       'work_ratings_count', 'work_text_reviews_count', 'ratings_1',
       'ratings_2', 'ratings_3', 'ratings_4', 'ratings_5', 'image_url',
       'small_image_url'],
      dtype='object')

In [9]:
books = books[['id', 'book_id','isbn',
       'isbn13', 'authors','title','average_rating', 'ratings_count','image_url',
       'small_image_url']]

In [10]:
book_tags = pd.read_csv('/book_tags.csv')
book_tags

goodreads_book_id  tag_id   count
0                       1   30574  167697
1                       1   11305   37174
2                       1   11557   34173
3                       1    8717   12986
4                       1   33114   12716
...                   ...     ...     ...
999907           33288638   21303       7
999908           33288638   17271       7
999909           33288638    1126       7
999910           33288638   11478       7
999911           33288638   27939       7

[999912 rows x 3 columns]

In [11]:
book_tags = book_tags.rename(columns={'goodreads_book_id':'book_id'})

In [12]:
tags = pd.read_csv('/tags.csv')
tags

tag_id    tag_name
0           0           -
1           1        --1-
2           2       --10-
3           3       --12-
4           4      --122-
...       ...         ...
34247   34247   Ｃhildrens
34248   34248   Ｆａｖｏｒｉｔｅｓ
34249   34249       Ｍａｎｇａ
34250   34250      ＳＥＲＩＥＳ
34251   34251  ｆａｖｏｕｒｉｔｅｓ

[34252 rows x 2 columns]

In [13]:
tagged_books = pd.merge(book_tags, tags, on='tag_id', how='inner')
tagged_books

book_id  tag_id   count     tag_name
0              1   30574  167697      to-read
1              2   30574   24549      to-read
2              3   30574  496107      to-read
3              5   30574   11909      to-read
4              6   30574     298      to-read
...          ...     ...     ...          ...
999907  31538635   14690       6     hogwarts
999908  32848471   16149      21     jan-2017
999909  33288638   27821       9   single-mom
999910  33288638   11478       7  fave-author
999911  33288638   27939       7     slowburn

[999912 rows x 4 columns]

In [14]:
new_tagged_books = tagged_books.groupby('book_id')['tag_name'].agg(lambda x: list(x)).reset_index()
new_tagged_books

book_id                                           tag_name
0            1  [to-read, fantasy, favorites, currently-readin...
1            2  [to-read, fantasy, favorites, currently-readin...
2            3  [to-read, fantasy, favorites, currently-readin...
3            5  [to-read, fantasy, favorites, currently-readin...
4            6  [to-read, fantasy, young-adult, fiction, harry...
...        ...                                                ...
9995  31538647  [to-read, fantasy, favorites, currently-readin...
9996  31845516  [to-read, favorites, currently-reading, fictio...
9997  32075671  [to-read, favorites, currently-reading, young-...
9998  32848471  [to-read, favorites, currently-reading, fictio...
9999  33288638  [to-read, favorites, currently-reading, fictio...

[10000 rows x 2 columns]

In [15]:
books_with_tags = pd.merge(books,new_tagged_books,on='book_id',how='inner')
books_with_tags

id  book_id        isbn        isbn13                      authors  \
0         1  2767052   439023483  9.780439e+12              Suzanne Collins   
1         2        3   439554934  9.780440e+12  J.K. Rowling, Mary GrandPré   
2         3    41865   316015849  9.780316e+12              Stephenie Meyer   
3         4     2657    61120081  9.780061e+12                   Harper Lee   
4         5     4671   743273567  9.780743e+12          F. Scott Fitzgerald   
...     ...      ...         ...           ...                          ...   
9995   9996  7130616   441019455  9.780441e+12                Ilona Andrews   
9996   9997   208324  067973371X  9.780680e+12               Robert A. Caro   
9997   9998    77431  039330762X  9.780393e+12              Patrick O'Brian   
9998   9999  8565083    61711527  9.780062e+12              Peggy Orenstein   
9999  10000     8914   375700455  9.780376e+12                  John Keegan   

                                                  title  average_rating  \
0               The Hunger Games (The Hunger Games, #1)            4.34   
1     Harry Potter and the Sorcerer's Stone (Harry P...            4.44   
2                               Twilight (Twilight, #1)            3.57   
3                                 To Kill a Mockingbird            4.25   
4                                      The Great Gatsby            3.89   
...                                                 ...             ...   
9995                          Bayou Moon (The Edge, #2)            4.09   
9996  Means of Ascent (The Years of Lyndon Johnson, #2)            4.25   
9997                              The Mauritius Command            4.35   
9998  Cinderella Ate My Daughter: Dispatches from th...            3.65   
9999                                The First World War            4.00   

      ratings_count                                          image_url  \
0           4780653  https://images.gr-assets.com/books/1447303603m...   
1           4602479  https://images.gr-assets.com/books/1474154022m...   
2           3866839  https://images.gr-assets.com/books/1361039443m...   
3           3198671  https://images.gr-assets.com/books/1361975680m...   
4           2683664  https://images.gr-assets.com/books/1490528560m...   
...             ...                                                ...   
9995          17204  https://images.gr-assets.com/books/1307445460m...   
9996          12582  https://s.gr-assets.com/assets/nophoto/book/11...   
9997           9421  https://images.gr-assets.com/books/1455373531m...   
9998          11279  https://images.gr-assets.com/books/1279214118m...   
9999           9162  https://images.gr-assets.com/books/1403194704m...   

                                        small_image_url  \
0     https://images.gr-assets.com/books/1447303603s...   
1     https://images.gr-assets.com/books/1474154022s...   
2     https://images.gr-assets.com/books/1361039443s...   
3     https://images.gr-assets.com/books/1361975680s...   
4     https://images.gr-assets.com/books/1490528560s...   
...                                                 ...   
9995  https://images.gr-assets.com/books/1307445460s...   
9996  https://s.gr-assets.com/assets/nophoto/book/50...   
9997  https://images.gr-assets.com/books/1455373531s...   
9998  https://images.gr-assets.com/books/1279214118s...   
9999  https://images.gr-assets.com/books/1403194704s...   

                                               tag_name  
0     [to-read, fantasy, favorites, currently-readin...  
1     [to-read, fantasy, favorites, currently-readin...  
2     [to-read, fantasy, favorites, currently-readin...  
3     [to-read, favorites, currently-reading, young-...  
4     [to-read, favorites, currently-reading, young-...  
...                                                 ...  
9995  [to-read, fantasy, favorites, currently-readin...  
9996  [to-read, favorites, currently-reading, books-...  
9997  [to-read, favorites, currently-re

In [16]:
books_with_tags['tags'] = books_with_tags.apply(lambda row: [row['authors']] + row['tag_name'], axis=1)
books_with_tags

id  book_id        isbn        isbn13                      authors  \
0         1  2767052   439023483  9.780439e+12              Suzanne Collins   
1         2        3   439554934  9.780440e+12  J.K. Rowling, Mary GrandPré   
2         3    41865   316015849  9.780316e+12              Stephenie Meyer   
3         4     2657    61120081  9.780061e+12                   Harper Lee   
4         5     4671   743273567  9.780743e+12          F. Scott Fitzgerald   
...     ...      ...         ...           ...                          ...   
9995   9996  7130616   441019455  9.780441e+12                Ilona Andrews   
9996   9997   208324  067973371X  9.780680e+12               Robert A. Caro   
9997   9998    77431  039330762X  9.780393e+12              Patrick O'Brian   
9998   9999  8565083    61711527  9.780062e+12              Peggy Orenstein   
9999  10000     8914   375700455  9.780376e+12                  John Keegan   

                                                  title  average_rating  \
0               The Hunger Games (The Hunger Games, #1)            4.34   
1     Harry Potter and the Sorcerer's Stone (Harry P...            4.44   
2                               Twilight (Twilight, #1)            3.57   
3                                 To Kill a Mockingbird            4.25   
4                                      The Great Gatsby            3.89   
...                                                 ...             ...   
9995                          Bayou Moon (The Edge, #2)            4.09   
9996  Means of Ascent (The Years of Lyndon Johnson, #2)            4.25   
9997                              The Mauritius Command            4.35   
9998  Cinderella Ate My Daughter: Dispatches from th...            3.65   
9999                                The First World War            4.00   

      ratings_count                                          image_url  \
0           4780653  https://images.gr-assets.com/books/1447303603m...   
1           4602479  https://images.gr-assets.com/books/1474154022m...   
2           3866839  https://images.gr-assets.com/books/1361039443m...   
3           3198671  https://images.gr-assets.com/books/1361975680m...   
4           2683664  https://images.gr-assets.com/books/1490528560m...   
...             ...                                                ...   
9995          17204  https://images.gr-assets.com/books/1307445460m...   
9996          12582  https://s.gr-assets.com/assets/nophoto/book/11...   
9997           9421  https://images.gr-assets.com/books/1455373531m...   
9998          11279  https://images.gr-assets.com/books/1279214118m...   
9999           9162  https://images.gr-assets.com/books/1403194704m...   

                                        small_image_url  \
0     https://images.gr-assets.com/books/1447303603s...   
1     https://images.gr-assets.com/books/1474154022s...   
2     https://images.gr-assets.com/books/1361039443s...   
3     https://images.gr-assets.com/books/1361975680s...   
4     https://images.gr-assets.com/books/1490528560s...   
...                                                 ...   
9995  https://images.gr-assets.com/books/1307445460s...   
9996  https://s.gr-assets.com/assets/nophoto/book/50...   
9997  https://images.gr-assets.com/books/1455373531s...   
9998  https://images.gr-assets.com/books/1279214118s...   
9999  https://images.gr-assets.com/books/1403194704s...   

                                               tag_name  \
0     [to-read, fantasy, favorites, currently-readin...   
1     [to-read, fantasy, favorites, currently-readin...   
2     [to-read, fantasy, favorites, currently-readin...   
3     [to-read, favorites, currently-reading, young-...   
4     [to-read, favorites, currently-reading, young-...   
...                                                 ...   
9995  [to-read, fantasy, favorites, currently-readin...   
9996  [to-read, favorites, currently-reading, books-...   
9997  [to-read, favorites, cur

In [17]:
books_with_tags = books_with_tags.drop(columns=['tag_name'],axis=1)

In [18]:
books_with_tags['tags'] = books_with_tags['tags'].apply(
    lambda tag_list: [tag.lower().replace(' ', '').replace('-', '').replace('.','').replace(',',' ') for tag in tag_list]
)
books_with_tags

id  book_id        isbn        isbn13                      authors  \
0         1  2767052   439023483  9.780439e+12              Suzanne Collins   
1         2        3   439554934  9.780440e+12  J.K. Rowling, Mary GrandPré   
2         3    41865   316015849  9.780316e+12              Stephenie Meyer   
3         4     2657    61120081  9.780061e+12                   Harper Lee   
4         5     4671   743273567  9.780743e+12          F. Scott Fitzgerald   
...     ...      ...         ...           ...                          ...   
9995   9996  7130616   441019455  9.780441e+12                Ilona Andrews   
9996   9997   208324  067973371X  9.780680e+12               Robert A. Caro   
9997   9998    77431  039330762X  9.780393e+12              Patrick O'Brian   
9998   9999  8565083    61711527  9.780062e+12              Peggy Orenstein   
9999  10000     8914   375700455  9.780376e+12                  John Keegan   

                                                  title  average_rating  \
0               The Hunger Games (The Hunger Games, #1)            4.34   
1     Harry Potter and the Sorcerer's Stone (Harry P...            4.44   
2                               Twilight (Twilight, #1)            3.57   
3                                 To Kill a Mockingbird            4.25   
4                                      The Great Gatsby            3.89   
...                                                 ...             ...   
9995                          Bayou Moon (The Edge, #2)            4.09   
9996  Means of Ascent (The Years of Lyndon Johnson, #2)            4.25   
9997                              The Mauritius Command            4.35   
9998  Cinderella Ate My Daughter: Dispatches from th...            3.65   
9999                                The First World War            4.00   

      ratings_count                                          image_url  \
0           4780653  https://images.gr-assets.com/books/1447303603m...   
1           4602479  https://images.gr-assets.com/books/1474154022m...   
2           3866839  https://images.gr-assets.com/books/1361039443m...   
3           3198671  https://images.gr-assets.com/books/1361975680m...   
4           2683664  https://images.gr-assets.com/books/1490528560m...   
...             ...                                                ...   
9995          17204  https://images.gr-assets.com/books/1307445460m...   
9996          12582  https://s.gr-assets.com/assets/nophoto/book/11...   
9997           9421  https://images.gr-assets.com/books/1455373531m...   
9998          11279  https://images.gr-assets.com/books/1279214118m...   
9999           9162  https://images.gr-assets.com/books/1403194704m...   

                                        small_image_url  \
0     https://images.gr-assets.com/books/1447303603s...   
1     https://images.gr-assets.com/books/1474154022s...   
2     https://images.gr-assets.com/books/1361039443s...   
3     https://images.gr-assets.com/books/1361975680s...   
4     https://images.gr-assets.com/books/1490528560s...   
...                                                 ...   
9995  https://images.gr-assets.com/books/1307445460s...   
9996  https://s.gr-assets.com/assets/nophoto/book/50...   
9997  https://images.gr-assets.com/books/1455373531s...   
9998  https://images.gr-assets.com/books/1279214118s...   
9999  https://images.gr-assets.com/books/1403194704s...   

                                                   tags  
0     [suzannecollins, toread, fantasy, favorites, c...  
1     [jkrowling marygrandpré, toread, fantasy, favo...  
2     [stepheniemeyer, toread, fantasy, favorites, c...  
3     [harperlee, toread, favorites, currentlyreadin...  
4     [fscottfitzgerald, toread, favorites, currentl...  
...                                                 ...  
9995  [ilonaandrews, toread, fantasy, favorites, cur...  
9996  [robertacaro, toread, favorites, currentlyread...  
9997  [patricko'brian, toread, favorite

In [19]:
books_with_tags['tags'] = books_with_tags['tags'].apply(lambda x: " ".join(x))
books_with_tags

id  book_id        isbn        isbn13                      authors  \
0         1  2767052   439023483  9.780439e+12              Suzanne Collins   
1         2        3   439554934  9.780440e+12  J.K. Rowling, Mary GrandPré   
2         3    41865   316015849  9.780316e+12              Stephenie Meyer   
3         4     2657    61120081  9.780061e+12                   Harper Lee   
4         5     4671   743273567  9.780743e+12          F. Scott Fitzgerald   
...     ...      ...         ...           ...                          ...   
9995   9996  7130616   441019455  9.780441e+12                Ilona Andrews   
9996   9997   208324  067973371X  9.780680e+12               Robert A. Caro   
9997   9998    77431  039330762X  9.780393e+12              Patrick O'Brian   
9998   9999  8565083    61711527  9.780062e+12              Peggy Orenstein   
9999  10000     8914   375700455  9.780376e+12                  John Keegan   

                                                  title  average_rating  \
0               The Hunger Games (The Hunger Games, #1)            4.34   
1     Harry Potter and the Sorcerer's Stone (Harry P...            4.44   
2                               Twilight (Twilight, #1)            3.57   
3                                 To Kill a Mockingbird            4.25   
4                                      The Great Gatsby            3.89   
...                                                 ...             ...   
9995                          Bayou Moon (The Edge, #2)            4.09   
9996  Means of Ascent (The Years of Lyndon Johnson, #2)            4.25   
9997                              The Mauritius Command            4.35   
9998  Cinderella Ate My Daughter: Dispatches from th...            3.65   
9999                                The First World War            4.00   

      ratings_count                                          image_url  \
0           4780653  https://images.gr-assets.com/books/1447303603m...   
1           4602479  https://images.gr-assets.com/books/1474154022m...   
2           3866839  https://images.gr-assets.com/books/1361039443m...   
3           3198671  https://images.gr-assets.com/books/1361975680m...   
4           2683664  https://images.gr-assets.com/books/1490528560m...   
...             ...                                                ...   
9995          17204  https://images.gr-assets.com/books/1307445460m...   
9996          12582  https://s.gr-assets.com/assets/nophoto/book/11...   
9997           9421  https://images.gr-assets.com/books/1455373531m...   
9998          11279  https://images.gr-assets.com/books/1279214118m...   
9999           9162  https://images.gr-assets.com/books/1403194704m...   

                                        small_image_url  \
0     https://images.gr-assets.com/books/1447303603s...   
1     https://images.gr-assets.com/books/1474154022s...   
2     https://images.gr-assets.com/books/1361039443s...   
3     https://images.gr-assets.com/books/1361975680s...   
4     https://images.gr-assets.com/books/1490528560s...   
...                                                 ...   
9995  https://images.gr-assets.com/books/1307445460s...   
9996  https://s.gr-assets.com/assets/nophoto/book/50...   
9997  https://images.gr-assets.com/books/1455373531s...   
9998  https://images.gr-assets.com/books/1279214118s...   
9999  https://images.gr-assets.com/books/1403194704s...   

                                                   tags  
0     suzannecollins toread fantasy favorites curren...  
1     jkrowling marygrandpré toread fantasy favorite...  
2     stepheniemeyer toread fantasy favorites curren...  
3     harperlee toread favorites currentlyreading yo...  
4     fscottfitzgerald toread favorites currentlyrea...  
...                                                 ...  
9995  ilonaandrews toread fantasy favorites currentl...  
9996  robertacaro toread favorites currentlyreading ...  
9997  patricko'brian toread favorites c

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
vectorizer = CountVectorizer(max_features=5000, stop_words='english')

In [22]:
vectors = vectorizer.fit_transform(books_with_tags['tags']).toarray()

In [23]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
similarity_score = cosine_similarity(vectors)
similarity_score

array([[1.        , 0.50926199, 0.55300126, ..., 0.35755905, 0.23222618,
        0.1633674 ],
       [0.50926199, 1.        , 0.46750958, ..., 0.35171166, 0.17096515,
        0.16612466],
       [0.55300126, 0.46750958, 1.        , ..., 0.24945181, 0.13459548,
        0.15386436],
       ...,
       [0.35755905, 0.35171166, 0.24945181, ..., 1.        , 0.21273174,
        0.29845644],
       [0.23222618, 0.17096515, 0.13459548, ..., 0.21273174, 1.        ,
        0.27833497],
       [0.1633674 , 0.16612466, 0.15386436, ..., 0.29845644, 0.27833497,
        1.        ]])

In [26]:
list(enumerate(similarity_score))

[(0,
  array([1.        , 0.50926199, 0.55300126, ..., 0.35755905, 0.23222618,
         0.1633674 ])),
 (1,
  array([0.50926199, 1.        , 0.46750958, ..., 0.35171166, 0.17096515,
         0.16612466])),
 (2,
  array([0.55300126, 0.46750958, 1.        , ..., 0.24945181, 0.13459548,
         0.15386436])),
 (3,
  array([0.40193938, 0.44730307, 0.36623351, ..., 0.37442566, 0.21840756,
         0.19765946])),
 (4,
  array([0.41284404, 0.4214582 , 0.3778842 , ..., 0.38735564, 0.23222618,
         0.19399879])),
 (5,
  array([0.59361349, 0.47198037, 0.4679096 , ..., 0.37570397, 0.29340579,
         0.19311496])),
 (6,
  array([0.48292085, 0.60504202, 0.4234049 , ..., 0.35171166, 0.20515818,
         0.1758967 ])),
 (7,
  array([0.40582294, 0.41549494, 0.37925342, ..., 0.32695644, 0.17457662,
         0.19956926])),
 (8,
  array([0.46207279, 0.3593135 , 0.36749727, ..., 0.42729202, 0.20618457,
         0.23570226])),
 (9,
  array([0.44954128, 0.48292085, 0.38710088, ..., 0.45688101, 0.2768

In [37]:
def rec(book_name):
  index = books[books['title'] == book_name].index[0]
  similar_books = similarity_score[index]
  similar_books = sorted(list(enumerate(similar_books)), key=lambda x: x[1], reverse=True)
  recs = []
  for book in similar_books:
    recs.append(book[0])
  recommendations = books_with_tags.loc[recs]
  return recommendations[1:11]

In [39]:
rec('The Mysterious Island (Extraordinary Voyages, #12)')

id  book_id        isbn        isbn13  \
698    699    33507  076072850X  9.780761e+12   
971    972    32829   553213970  9.780553e+12   
705    706    54479  014044906X  9.780140e+12   
7615  7616  1219103  1421820609  9.781422e+12   
6821  6822    32827  1598184547  9.781598e+12   
2552  2553    10155   812967259  9.780813e+12   
1203  1204    17184   451528522  9.780452e+12   
3126  3127    50033   671037706  9.780671e+12   
3832  3833    40425   809599813  9.780810e+12   
297    298     2493   451528557  9.780452e+12   

                                              authors  \
698                       Jules Verne, Anthony Bonner   
971                                       Jules Verne   
705   Jules Verne, Michael Glencross, Brian W. Aldiss   
7615                                      Jules Verne   
6821                                      Jules Verne   
2552                               Arthur Conan Doyle   
1203                                       H.G. Wells   
3126                                     Ray Bradbury   
3832                             Edgar Rice Burroughs   
297              H.G. Wells, Greg Bear, Carlo Pagetti   

                                                  title  average_rating  \
698               Twenty Thousand Leagues Under the Sea            3.86   
971   Journey to the Center of the Earth (Extraordin...            3.84   
705                     Around the World in Eighty Days            3.90   
7615  Five Weeks in a Balloon (Extraordinary Voyages...            3.74   
6821  From the Earth to the Moon (Extraordinary Voya...            3.78   
2552          The Lost World (Professor Challenger, #1)            3.92   
1203                                  The Invisible Man            3.62   
3126                    Dandelion Wine (Green Town, #1)            4.08   
3832                    Tarzan of the Apes (Tarzan, #1)            3.88   
297                                    The Time Machine            3.87   

      ratings_count                                          image_url  \
698          121112  https://images.gr-assets.com/books/1494979127m...   
971           89410  https://s.gr-assets.com/assets/nophoto/book/11...   
705          117108  https://images.gr-assets.com/books/1308815551m...   
7615          13062  https://s.gr-assets.com/assets/nophoto/book/11...   
6821          14721  https://s.gr-assets.com/assets/nophoto/book/11...   
2552          39169  https://images.gr-assets.com/books/1320504012m...   
1203          84778  https://s.gr-assets.com/assets/nophoto/book/11...   
3126          32867  https://images.gr-assets.com/books/1374049845m...   
3832          27529  https://s.gr-assets.com/assets/nophoto/book/11...   
297          276076  https://images.gr-assets.com/books/1327942880m...   

                                        small_image_url  \
698   https://images.gr-assets.com/books/1494979127s...   
971   https://s.gr-assets.com/assets/nophoto/book/50...   
705   https://images.gr-assets.com/books/1308815551s...   
7615  https://s.gr-assets.com/assets/nophoto/book/50...   
6821  https://s.gr-assets.com/assets/nophoto/book/50...   
2552  https://images.gr-assets.com/books/1320504012s...   
1203  https://s.gr-assets.com/assets/nophoto/book/50...   
3126  https://images.gr-assets.com/books/1374049845s...   
3832  https://s.gr-assets.com/assets/nophoto/book/50...   
297   https://images.gr-assets.com/books/1327942880s...   

                                                   tags  
698   julesverne anthonybonner toread fantasy favori...  
971   julesverne toread fantasy favorites currentlyr...  
705   julesverne michaelglencross brianwaldiss torea...  
7615  julesverne toread fantasy favorites currentlyr...  
6821  julesverne toread fantasy favorites currentlyr...  
2552  arthurconandoyle toread fantasy favorites curr...  
1203  hgwells toread fantasy favorites currentlyread...  
3126  raybradbury toread fantasy favorites currently...  
3832  edgarriceburroughs to

In [29]:
import pickle

In [30]:
with open('books.pkl', 'wb') as f:
    pickle.dump(books, f)

with open('similarity_score.pkl', 'wb') as f:
    pickle.dump(similarity_score, f)

In [31]:
from google.colab import files
files.download('books.pkl')
files.download('similarity_score.pkl')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>